apiVersion: apps/v1
kind: Deployment
metadata:
  name: opika-deployment
  labels:
    app: opika
spec:
  selector:
    matchLabels:
      app: opika
  template:
    metadata:
      labels:
        app: opika
    spec:
      serviceAccountName: s3-backup  # Attach the service account here
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: scrapy
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: opika
        image: docker.io/ajitsingh25/opika:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
