apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scrapy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scrapy-deployment  # Update to match the name of your Deployment
  minReplicas: 1  # Minimum number of pods
  maxReplicas: 3  # Maximum number of pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Target 50% CPU utilization