apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi  # This is symbolic; EFS can scale automatically
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Allows multiple pods to write to the same volume
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "efs-sc"
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <file-system-id>  # Replace with your Amazon EFS File System ID
