apiVersion: v1
kind: ServiceAccount
metadata:
  name: opika-service-account
  namespace: default  # Change if you're using a different namespace
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::767397854891:role/dev_s3_backup_role
