apiVersion: v1
kind: Service
metadata:
  name: opika-service
spec:
  type: NodePort  # Use NodePort to expose the service externally
  selector:
    app: opika
  ports:
    - port: 5000       # The port that the service will expose
      targetPort: 5000 # The port that the container listens on
      nodePort: 30000   # The port to access the service on the node (optional)
